language: python

python:
- '3.4'
- '3.5'
- '3.6'

install: true

env:
  global:
    - REPOSITORY_USER=DiegoPomares
    - secure: "DhFHhwO++dGidJshsuGxF9u5/PvdblLvEPc2XHKQyFJMNk/ch4XrgFm/bmqAq3saSFpoepmLAqqenmss4iB0BbAPaOCW2zeIa+hGIs9w8TvxORkLMXp04XVjGjG/09YhuFclBDT9eqYB0uqRTQb4aruKPigGBzfC9o8TMUqL4JH9IHQoWnu39zD2gOjPJ4MwPxZwKKZH9MtBz4R8DiadtjkHDMZG70YtHYTgalPrwtKzBzfSXeMQDFF7QP6xXQse6F6xcVge7gIw04gl6DIf/HWpWfqDSXYio4weLABg8GwNZfpxtTuBKcd/UA2qXRuSRX9LvtQ7ypkXHIw2kihZGs85FZqgTbn0AErbmpOylb7N+1mF4I4/K9sJKjwdnT1obCrkiJP1OdxaWaDTlXJT6RDgPAOMK4tNhxomi7pRLWu+3L15JOxxM+rupsr3GX1SxgsbmQd+2Xk6/w6dIMj67gQTEnSWAJdX6E0t9Cn6cnrOvGf4M4nORkngIQRubstA3iT7pCGpNTZ1Jq+q5sTPl7TDJGgANBEVth2CnN0TQJVP/HkTZCXNuRPdf1CaOR90c2vENQI+Gv9SO5jWYdg/kdtOs4dfvAD8XO6m9PL1s8dlRyRHYQHp3Nh9M+/ZMRvq4yi4PShbJCuvFdGftIXmRRSauwcnqjeN2JtmgspVsLs="

script:
- "./script/cibuild"

deploy:
  - provider: script
    skip_cleanup: true
    script: ./script/cideploy
    on:
      python: 3.6
      tags: true
