#!/bin/sh

set -e


cd "$(dirname "$(readlink -f "$0")")/.."

if [ -z "$TRAVIS" ]; then
	echo "$0 should only be used in a CI environment like TravisCI"
	exit 1
fi

mkdir -p reports
cd reports

python ../test/run.py -k test/unit/
codecov -F unit

python ../test/run.py -k test/integration/
codecov -F integration

python ../test/run.py -k test/acceptance/
codecov -F acceptance
