#!/bin/sh

set -e


cd "$(dirname "$(readlink -f "$0")")/.."

if [ -z "$TRAVIS" ]; then
	echo "$0 should only be used in a CI environment like TravisCI"
	exit 1
fi

# Don't run tests, just the linter
python test/run.py --ignore=test

# Run tests
mkdir -p reports
cd reports

for kind in unit integration acceptance; do
	python ../test/run.py --no-lint -k "test/$kind/"
	codecov -F "$kind"
done
