#!/bin/sh

set -xe


cd "$(dirname "$(readlink -f "$0")")/.."

if [ -z "$TRAVIS" ]; then
	echo "$0 should only be used in a CI environment like TravisCI"
    exit 1
fi

trap "{ rm -f ~/.pypirc; exit 0; }" EXIT

touch ~/.pypirc
chmod 600 ~/.pypirc
cat >> ~/.pypirc <<EOF
[distutils]
index-servers =
    repository

[repository]
username: ${REPOSITORY_USER}
password: ${REPOSITORY_PWD}
EOF

python setup.py sdist bdist_wheel upload -r repository
